include: package:very_good_analysis/analysis_options.yaml


analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**test/.test_coverage.dart"
    - "**bin/cache/**"