include: package:very_good_analysis/analysis_options.yaml

analysis:
  exclude: 
    - test/**/*_test.dart
    - lib/generated/**
    - "**/*.g.dart"
    - "/*.gen.dart"
    - "/*.freezed.dart" 
    - "bin/cache/**"
  