name: flutter_architecture_template
description: "A new Flutter Architecture Template project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## Core
  equatable: ^2.0.5


  ## Network
  vexana: ^4.0.1

  ## Utility
  kartal: ^3.5.0
  logger: ^2.2.0
  google_fonts: ^6.2.1
  
  #Config
  easy_localization: ^3.0.5

  ## state
  flutter_bloc: ^8.1.5

  #Navigation
  auto_route: ^8.0.2
  auto_route_generator: ^8.0.0

  widgets:
    path: module/widgets
  gen:
    path: module/gen
  common:
    path: module/common

dependency_overrides:
  ## Add your dependency overrides here.

dev_dependencies:
  ## test unit test, icon generation, file generation packages are written here.
  flutter_test: 
    sdk: flutter
  very_good_analysis: ^5.1.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9
  device_preview: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/translations/